var OwnerData = [
    {"id": "Owners", "parent": "#", "text": "Owners"},
    {"id": "Boots UK Limited" , "parent": "Owners", "text": "Boots UK Limited"},
    {"id": "Lloyds Pharmacy Ltd" , "parent": "Owners", "text": "Lloyds Pharmacy Ltd"},
    {"id": "L Rowland & Co (Retail) Ltd" , "parent": "Owners", "text": "L Rowland & Co (Retail) Ltd"},
    {"id": "Bestway National Chemists Limited" , "parent": "Owners", "text": "Bestway National Chemists Limited"},
    {"id": "Tesco Stores Ltd" , "parent": "Owners", "text": "Tesco Stores Ltd"},
    {"id": "Asda Stores Ltd" , "parent": "Owners", "text": "Asda Stores Ltd"},
    {"id": "Bestway Panacea Healthcare Limited" , "parent": "Owners", "text": "Bestway Panacea Healthcare Limited"},
    {"id": "Day Lewis Plc" , "parent": "Owners", "text": "Day Lewis Plc"},
    {"id": "Superdrug Stores Plc" , "parent": "Owners", "text": "Superdrug Stores Plc"},
    {"id": "Gorgemead Ltd" , "parent": "Owners", "text": "Gorgemead Ltd"},
    {"id": "W M Morrison Supermarkets Plc" , "parent": "Owners", "text": "W M Morrison Supermarkets Plc"},
    {"id": "Paydens Ltd" , "parent": "Owners", "text": "Paydens Ltd"},
    {"id": "PCT Healthcare Limited" , "parent": "Owners", "text": "PCT Healthcare Limited"},
    {"id": "H. I. Weldrick Ltd" , "parent": "Owners", "text": "H. I. Weldrick Ltd"},
    {"id": "Dudley Taylor Pharmacies Ltd" , "parent": "Owners", "text": "Dudley Taylor Pharmacies Ltd"},
    {"id": "Waremoss Ltd" , "parent": "Owners", "text": "Waremoss Ltd"},
    {"id": "Lincoln Co-operative Chemists Ltd" , "parent": "Owners", "text": "Lincoln Co-operative Chemists Ltd"},
    {"id": "WR Evans Healthcare Ltd" , "parent": "Owners", "text": "WR Evans Healthcare Ltd"},
    {"id": "Rajja Ltd" , "parent": "Owners", "text": "Rajja Ltd"},
    {"id": "West Midlands Co-operative Chemists Ltd" , "parent": "Owners", "text": "West Midlands Co-operative Chemists Ltd"},
    {"id": "Other" , "parent": "Owners", "text": "Other"}
];